//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListLibrary {
  using System;
  using System.ComponentModel.DataAnnotations.Schema;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;
  using System.IO;

  public partial class toDoListConnectionString : DbContext {

    #region Constructor

    public toDoListConnectionString()
      : base(ConnectionStringToDatabase()) { }

    #endregion

    protected override void OnModelCreating(DbModelBuilder modelBuilder) {

      modelBuilder.Entity<Tasks>()
        .Property(t => t.Id)
        .HasColumnType("bigint");

      modelBuilder.Entity<Tasks>()
        .Property(t => t.Check)
        .HasColumnType("bigint");

      throw new UnintentionalCodeFirstException();
    }

    #region Static method

    private static string ConnectionStringToDatabase() {
      string projectDir = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.FullName;
      string relativePath = Path.Combine(projectDir, @"ToDoListLibrary\Database\ToDoListDatabase.db");
      string dataSource = string.Format("data source={0}", relativePath);
      string connectionString = string.Format("metadata=res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl;provider=System.Data.SQLite.EF6;provider connection string='{0}'", dataSource);

      return connectionString;
    }

    #endregion

    #region Database models

    public virtual DbSet<Tasks> Tasks { get; set; }

    #endregion
  }
}
