//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListLibrary {
  using System;
  using System.ComponentModel.DataAnnotations.Schema;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;
    
  public partial class toDoListConnectionString : DbContext {
    public toDoListConnectionString()
      : base("name=toDoListConnectionString") { }
    
    protected override void OnModelCreating(DbModelBuilder modelBuilder) {

      modelBuilder.Entity<Tasks>()
        .Property(t => t.Id)
        .HasColumnType("bigint");

      modelBuilder.Entity<Tasks>()
        .Property(t => t.Check)
        .HasColumnType("bigint");

      throw new UnintentionalCodeFirstException();
    }
    
    public virtual DbSet<Tasks> Tasks { get; set; }
  }
}
